<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="14716" started-at="2020-09-26T20:28:47 IST" finished-at="2020-09-26T20:29:01 IST">
    <groups>
    </groups>
    <test name="NoonAssignment" duration-ms="14716" started-at="2020-09-26T20:28:47 IST" finished-at="2020-09-26T20:29:01 IST">
      <class name="org.noon.TrxnHistoryTests">
        <test-method status="PASS" signature="trxnHistorySuccess()[pri:1, instance:org.noon.TrxnHistoryTests@35083305]" name="trxnHistorySuccess" duration-ms="1548" started-at="2020-09-26T20:28:57 IST" finished-at="2020-09-26T20:28:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- trxnHistorySuccess -->
        <test-method status="PASS" signature="setup()[pri:0, instance:org.noon.TrxnHistoryTests@35083305]" name="setup" is-config="true" duration-ms="0" started-at="2020-09-26T20:28:57 IST" finished-at="2020-09-26T20:28:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="trxnHistoryError()[pri:2, instance:org.noon.TrxnHistoryTests@35083305]" name="trxnHistoryError" duration-ms="1497" started-at="2020-09-26T20:28:58 IST" finished-at="2020-09-26T20:29:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- trxnHistoryError -->
        <test-method status="FAIL" signature="trxnHistoryErrorStatus404Test()[pri:3, instance:org.noon.TrxnHistoryTests@35083305]" name="trxnHistoryErrorStatus404Test" duration-ms="1619" started-at="2020-09-26T20:29:00 IST" finished-at="2020-09-26T20:29:01 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Non message available] but found [No message available]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Non message available] but found [No message available]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.noon.TrxnHistoryTests.trxnHistoryErrorStatus404Test(TrxnHistoryTests.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- trxnHistoryErrorStatus404Test -->
      </class> <!-- org.noon.TrxnHistoryTests -->
      <class name="org.noon.ValidateTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:org.noon.ValidateTests@52e677af]" name="setup" is-config="true" duration-ms="1004" started-at="2020-09-26T20:28:47 IST" finished-at="2020-09-26T20:28:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="validateSuccess()[pri:1, instance:org.noon.ValidateTests@52e677af]" name="validateSuccess" duration-ms="7310" started-at="2020-09-26T20:28:48 IST" finished-at="2020-09-26T20:28:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSuccess -->
        <test-method status="PASS" signature="validateError()[pri:2, instance:org.noon.ValidateTests@52e677af]" name="validateError" duration-ms="1392" started-at="2020-09-26T20:28:55 IST" finished-at="2020-09-26T20:28:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateError -->
      </class> <!-- org.noon.ValidateTests -->
    </test> <!-- NoonAssignment -->
  </suite> <!-- Suite1 -->
</testng-results>
